spring.application.name=demojava100
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student 
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update